version: '3'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - examples-of-patterns-app
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated

networks:
  examples-of-patterns-app:
    driver: bridge